### ISSUE TITLE
Odd behavior when performing config:push relating to newlines

### ISSUE THREAD

**Issue by Plenglin** [xavdid/heroku-config#11]
Something weird happens with newlines when I push these `.env` files.

```
DISCORDTOKEN=foo
LOGLEVEL=20
HSAPI=bar
```
When I push this, the `DISCORDTOKEN` and `LOGLEVEL` lines will not be parsed correctly, but `HSAPI` will.

```
DISCORDTOKEN=foo
HSAPI=bar
LOGLEVEL=20
```
When I push this, the `DISCORDTOKEN` and `HSAPI` lines will not be parsed correctly, but `LOGLEVEL` will.

```
DISCORDTOKEN=foo
LOGLEVEL=20
HSAPI=bar

```
If I add a trailing newline, `HSAPI` also does not get parsed.

**Comment by xavdid** [comment]
Interesting!

The file reader splits by newline so it's weird that it parses worse when
there's an extra newline.

Would you mind emailing me (or providing a link to) the file itself?
Secrets redacted of course, but it would be useful to test against.

~DavidB
[davidbrownman.com]
c: 303.819.0850

**Comment by xavdid** [comment]
@Plenglin All right, sorry for the delay here! Your problem is twofold. 

The file you sent had windows-style line breaks (`\r\n`) instead of unix (`\n`), so that's why there was some weirdness with the newlines. I'll release a fix to handle that and you should be ok.

Secondly, your `hs-api` variable has an invalid name. Since heroku [runs on linux](https://devcenter.heroku.com/articles/stack#cedar), variable names must conform to those valid in [unix](https://stackoverflow.com/questions/2821043/allowed-characters-in-linux-environment-variable-names/2821183#2821183). I'd recommend `hs_api` instead. I'll make a note in the readme that clarifies this.

**Comment by xavdid** [comment]
Release is out, should be all set here. Thanks for the report!
